---
# Help : https://docs.ansible.com/ansible/latest/modules/network_maintained.html
# Module : /usr/lib/python3/dist-packages/ansible/modules/network
# Global Configuration
- hosts: SW
  gather_facts: no
  
  vars_files:
    - var.yml
 
  tasks: 
  
  - name: Enable feature VPC
    nxos_feature:
      feature: vpc
      state: enabled
  
  - name: Enable feature LACP
    nxos_feature:
      feature: lacp
      state: enabled

  - name: Create Port-channell 
    nxos_linkagg:
      aggregate:
        - { group: "{{ PoIDPeerLink }}" }
  
  - name: Enable PeerLink Po
    nxos_vpc_interface:
      portchannel: 100
      peer_link: true

  - name: Enable Jumbo 1/2
    nxos_config:
      lines:
        - mtu 9216
      parents: class type network-qos class-default
      before: policy-map type network-qos jumbo

  - name: Enable Jumbo 2/2
    nxos_config:
      lines:
        - service-policy type network-qos jumbo
      parents: system qos 


# Configuration SW primaire
- hosts: "{{ swprimary }}"
  gather_facts: no
  vars_files:
    - var.yml
 
  tasks: 
  - name: VPC configuration Sw Primaire
    nxos_vpc:
      domain: "{{ vpcdomain }}"
      role_priority: 1000
      pkl_dest: "{{ swsecondary }}"
      pkl_src: "{{ swprimary }}"
      peer_gw: false
      auto_recovery: true

  - name: Reset Int "{{ int1P }}"
    nxos_l2_interface:
      name: "{{ int1P }}"
      state: unconfigured

  - name: Reset Int "{{ int2P }}"
    nxos_l2_interface:
      name: "{{ int2P }}"
      state: unconfigured

  - name: Setup Interface PortGroup PeerLink Sw Primaire
    nxos_linkagg:
      group: "{{ PoIDPeerLink }}"
      mode: active
      members:
        - "{{ int1P }}"
        - "{{ int2P }}"

  - name: Trunk mode "{{ intPoPeerLink }}"
    nxos_l2_interface:
      name: "{{ intPoPeerLink }}"
      mode: trunk

  - name: Wr Mem
    nxos_command:
      commands: copy running-config startup-config
 
  - name: show port-channel summary
    nxos_command:
      commands: show port-channel summary
    register: stdout
  

# Configuration SW Secondary
- hosts: "{{ swsecondary }}"
  gather_facts: no
  vars_files:
    - var.yml
 
  tasks: 
  - name: VPC configuration Sw Secondary
    nxos_vpc:
      domain: "{{ vpcdomain }}"
      role_priority: 2000
      pkl_dest: "{{ swprimary }}"
      pkl_src: "{{ swsecondary }}"
      peer_gw: false
      auto_recovery: true

  - name: Reset Int "{{ int1S }}"
    nxos_l2_interface:
      name: "{{ int1S }}"
      state: unconfigured

  - name: Reset Int "{{ int2S }}"
    nxos_l2_interface:
      name: "{{ int2S }}"
      state: unconfigured


  - name: Setup Interface PortGroup PeerLink Sw Secondary
    nxos_linkagg:
      group: "{{ PoIDPeerLink }}"
      mode: active
      members:
        - "{{ int1S }}"
        - "{{ int2S }}"

  - name: Trunk mode "{{ intPoPeerLink }}"
    nxos_l2_interface:
      name: "{{ intPoPeerLink }}"
      mode: trunk

  - name: Wr Mem
    nxos_command:
      commands: copy running-config startup-config

  - debug:
      var: stdout.stdout_lines



